name: todomvc
description: TodoMVC written for Flutter

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^2.0.0
  firebase_auth: ^0.4.0

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
